language: python

python:
    - "2.7"

services:
    - "mysql"

install:
    - "pip install -r req-travis.txt"

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install python-mysqldb"
    - "sudo apt-get install python-dev"

before_script:
    - "mysql -e 'CREATE DATABASE coursedb;'" # create db
    - "mysql -u root -e \"CREATE USER 'tetrabyte'@'localhost' IDENTIFIED BY 'test';\""
    - "mysql -u root -e 'CREATE DATABASE coursedb;'"
    - "mysql -u root -e \"GRANT ALL ON coursedb.* TO tetrabyte\""

script:
    - "cd utils"
    - "python database_setup.py -l ../sample_data/smaller_grad_req.xlsx" # Set up test db
    - "python database.py" # run main
