PROJECT_DB_NAME = "coursedb"
COURSES_TABLE_NAME = "courses"
STUDENT_TABLE_NAME = "students"

COURSES_TABLE_COLUMNS = ["STUDENTID", "SCHOOL", "YEAR", "TERM", "COURSE", "COURSE_TITLE", "MARK", "CREDITS"]

STUDENT_TABLE_COLUMNS = ["STUDENTID", "LASTNAME", "FIRSTNAME", "GRADE", "OFFCLASS"]

TOTAL_REQ_COUNT = 7 # amount of graduation requirements
